name: Print all project files

on:
  workflow_dispatch:

jobs:
  print-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
  
    - name: Print
      run: pwd; ls -lah
