name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Specify the version of .NET you are using

    
    - name: Restore dependencies
      run: dotnet restore SportsGoalApp/SportsGoalAppTests.csproj

    
    - name: Build
      run: dotnet build --no-restore

    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
