name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Specify the version of .NET you are using

    
    - name: Restore dependencies
      run: dotnet restore SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj

    
    - name: Build
      run: dotnet build SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj --no-restore

    
    - name: Test
      env:
        ChatGpt__ApiKey: ${{ secrets.API_KEY }}
      run: dotnet test SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj --no-build --verbosity normal
    
