name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "Abc@123"
          ACCEPT_EULA: "A"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Specify the version of .NET you are using

    
    - name: Restore dependencies
      run: dotnet restore SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj

    
    - name: Build
      run: dotnet build SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj --no-restore

    
    - name: Test
      env:
        ChatGpt__ApiKey: ${{ secrets.API_KEY }}
        ConnectionStrings: Server=.\\SQLEXPRESS;Database=SportsGoalApp;Trusted_Connection=True; Encrypt=false
      run: dotnet test SportsGoalApp/SportsGoalAppTests/SportsGoalAppTests.csproj 
    
