name: OpenAIApi Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SportsGoalApp/OpenAIAPITests/OpenAIAPITests.csproj

    - name: Build
      run: dotnet build SportsGoalApp/OpenAIAPITests/OpenAIAPITests.csproj --no-restore

    - name: Run integration tests
      run: dotnet test SportsGoalApp/OpenAIAPITests/OpenAIAPITests.csproj --no-build --verbosity normal
    
    

    
